### ISSUE TITLE
what's different compared to SoftPosits.jl ?

### ISSUE THREAD

**Issue by chakravala** [takum-arithmetic/Posits.jl#4]
Would be useful to know how this differs from https://github.com/milankl/SoftPosit.jl

**Comment by hunhold** [comment]
The main difference is that Posits.jl exposes a 64-bit posit type and also has a full set of logarithmic posit types, which have become more relevant in recent years. It also benefits from full test coverage via libposit, which already exposed some rare bugs in SoftPosits.jl which I will report as soon as I get around to it.

I'm sure you are familiar with those differences, and I wrote them down here just a a marker to add them to the README at some point. Thanks for raising this issue, this is an important aspect!

**Comment by chakravala** [comment]
I don't know much about posits, never used them before, your package has initiated my curiosity. Yes 64 bit seems important. Feel free to close this issue at your own discretion.

**Comment by hunhold** [comment]
Dear @chakravala, thanks again for your report! I added the information to the README.
